update documentation
hove-io/navitia_sdk_docs pull request #143
Opened 2024-09-13 13:29 UTC by hirsch-adeline

2024-09-16 06:48 UTC, EvenModiguy requested changes

2024-09-16 06:48 UTC, EvenModiguy commented on README.md
> +First set up a virtual env by the following commands :
Il n'y a pas d'espace avant les 2 points en anglais.

2024-09-16 06:48 UTC, EvenModiguy commented on docs/around_me/ios/index.md
> +`Around Me` module communicates with [Bookmark](../../bookmark/ios) module in order to vizualize favorite stations, POIs and journeys. You should enable the `bookmark_mode` parameter in the [features
```suggestion
Around Me module communicates with [Bookmark](../../bookmark/ios) module in order to vizualize favorite stations, journeys and POIs. You should enable the `bookmark_mode` parameter in the [features configuration](../../getting_started/#around-me-features).<br>
```

2024-09-16 06:48 UTC, EvenModiguy commented on docs/around_me/ios/index.md
> +`Around me` module communicates with [Journey](../../journey/ios) module in order to get directions for a chosen itinerary. You should enable the `journey_mode` and the `go_from_go_to` parameter in t
```suggestion
Around me module communicates with [Journey](../../journey/ios) module in order to get directions for a chosen itinerary. You should enable the `journey_mode` and the `go_from_go_to` parameter in the [features configuration](../../getting_started/#around-me-features).<br>
```

2024-09-16 06:48 UTC, EvenModiguy commented on docs/bookmark/ios/index.md
> +    )
L'indentation n'est pas bonne. Elle doit être de 4 espaces, non de 2.

2024-09-16 14:02 UTC, hirsch-adeline commented on docs/around_me/ios/index.md
> +The following methods from the `CustomAroundMeBookmarkDelegate` interface should be implemented by the host application to enable navigation to the Bookmark module or any other custom screen. Note th
par défault, si tu n'implémente pas le delegate, c'est notre bookmark qui s'affiche. le delegate a été crée uniquement dans le but d'afficher un écran de l'intégrateur.

2024-09-16 14:03 UTC, hirsch-adeline commented on docs/around_me/ios/index.md
> +This method is called after click on the favorite home shortcut button, in case it is empty.
je concoit... je preferes laisser cette phrase en attendant qu'on renomme la méthode ?

2024-09-17 08:36 UTC, EvenModiguy requested changes

2024-09-17 08:36 UTC, EvenModiguy commented on docs/around_me/ios/index.md
> +This method is called after click on the favorite home shortcut button, in case it is empty.
No problem

2024-09-17 08:36 UTC, EvenModiguy commented on docs/bookmark/ios/index.md
>            .initialize()
Je crois que l'indentation n'est pas bonne

2024-09-17 08:36 UTC, EvenModiguy commented on README.md
> +Run this URL ``http://127.0.0.1:8000/navitia_sdk_docs`/` in your browser.
```suggestion
Run this URL `http://127.0.0.1:8000/navitia_sdk_docs/` in your browser.
```

2024-09-17 08:36 UTC, EvenModiguy commented on docs/around_me/ios/index.md
> +        .initialize()
Il me semble que l'indentation n'est pas bonne

2024-09-17 12:32 UTC, EvenModiguy approved these changes

2024-09-17 12:39 UTC, merged